/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Card: typeof import('./src/components/Card.vue')['default']
    Container: typeof import('./src/components/Container.vue')['default']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Menu: typeof import('./src/components/Menu.vue')['default']
    ReloadPrompt: typeof import('./src/components/ReloadPrompt.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Swiper: typeof import('./src/components/Swiper.vue')['default']
    UserProfile: typeof import('./src/components/user/Profile.vue')['default']
  }
}

// For TSX support
declare global {
  const Card: typeof import('./src/components/Card.vue')['default']
  const Container: typeof import('./src/components/Container.vue')['default']
  const ElAvatar: typeof import('element-plus/es')['ElAvatar']
  const HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
  const Menu: typeof import('./src/components/Menu.vue')['default']
  const ReloadPrompt: typeof import('./src/components/ReloadPrompt.vue')['default']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
  const Swiper: typeof import('./src/components/Swiper.vue')['default']
  const UserProfile: typeof import('./src/components/user/Profile.vue')['default']
}